#!/bin/bash

while [[ $# > 0 ]]
do
key="$1"

case $key in
    -l|--wget-command_from_ccg)
    f=${2}
    shift # past argument
    ;;
    -o|--output_folder)
    folder=${2}
    shift # past argument
    ;;
    *)
    ;;
esac
shift # past argument or value
done

if [[ ! -d ${folder} ]]; then
mkdir -p ${folder}; fi
folder=$(readlink -f ${folder}) 

cd ${folder}
${f}

target=bastet.ccg.uni-koeln.de/downloads/
user=$(ls -d ${target}*/)
mv ${user}*.fq.gz .
mv ${user}checksums/*.md5 .
rm -rf bastet.ccg.uni-koeln.de
for i in $(ls *.md5); do echo "$(cat ${i})  ${i::(-4)}" >> md5.tmp; done
md5sum -c md5.tmp 2>&1 | tee md5.log
echo $(date) >> downloads.log
cat md5.log >> downloads.log
rm md5.log md5.tmp
exit


  

