#!/bin/bash

ip=$(ifconfig | grep "inet 134")
ip=${ip:13:15}

port=$(cat ~/.ipython/profile_nbserver/ipython_notebook_config.py | grep "c.NotebookApp.port =")
port=${port:21:4}

echo "

iPython notebook running on:

https://${ip}:${port}/login


"

ipython notebook --profile=nbserver 


